version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: fluxo_caixa_api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - dynamodb
      - localstack

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,lambda,apigateway
      - DEFAULT_REGION=us-east-1

  worker:
    image: mcr.microsoft.com/dotnet/runtime:6.0
    container_name: fluxo_caixa_worker
    environment:
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/fluxo-caixa-queue
    depends_on:
      - localstack
